import React from 'react';
import Navbar from "./(components)/Navbar";
import Footer from "./(components)/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import bg2 from "./(components)/images/bg1.png";
// import bg2 from "./(components)/images/d.jpg";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yudiz Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: "url(" + `${bg2.src}` + ")",
          width: "100%",
          height: "80%",
          position: "sticky",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          
        }}
        className={inter.className}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
